version: "3.8"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    command: npm run dev

  # back:
  #   # ここではまだ実装例としてのみ定義しています
  #   # build:
  #   #   context: ./back
  #   #   dockerfile: Dockerfile
  #   # ports:
  #   #   - "3001:3001"
  #   # command: bin/rails server -b 0.0.0.0
  #   # environment:
  #   #   - DB_HOST=db
  #   #   - DB_USER=postgres
  #   #   - DB_PASSWORD=postgres
  #   #   - DB_NAME=app_development
  #   image: "rails:latest"
