FROM ruby:3.2.2-slim

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libpq-dev nodejs npm git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリの作成
WORKDIR /app

# GemfileとGemfile.lockをコピー（開発環境用）
COPY Gemfile ./
RUN touch Gemfile.lock

# Bundlerの設定とGemのインストール
RUN gem install bundler
RUN bundle config set --local without 'production'

# アプリケーションのソースをコピー
COPY . .

# サーバー起動用のスクリプトに実行権限を付与
RUN chmod +x /app/bin/rails

# コンテナ起動時に実行するコマンド
CMD ["rails", "server", "-b", "0.0.0.0"]