FROM ruby:3.3.0

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs curl postgresql-client

# 作業ディレクトリの設定
WORKDIR /app

# GemfileとGemfile.lockをコピー
COPY Gemfile ./
COPY Gemfile.lock ./

# bundle installの実行（バインドマウントされたgemを使用）
RUN bundle config set --local path '/usr/local/bundle' && \
    bundle install

# アプリケーションのコピー
COPY . .

# コンテナ起動時に実行するコマンド
CMD ["rails", "server", "-b", "0.0.0.0"]