name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: ./back

      - name: Setup Database
        working-directory: ./back
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run backend tests
        working-directory: ./back
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          bin/rails test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./front/package-lock.json"

      - name: Install frontend dependencies
        working-directory: ./front
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: test
        run: |
          npm ci
          npm install @next/swc-linux-x64-gnu

      - name: Run frontend tests
        working-directory: ./front
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: test
        run: npm test
